language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - 0.10

env:
  global:
    - ATOM_ACCESS_TOKEN=da809a6077bb1b0aa7c5623f7b2d5f1fec2faae4

branches:
  only:
    - gh-pages
