title: Electron
email: electron@github.com
description: 'Build cross platform desktop apps with JavaScript, HTML, and CSS.'
url: 'http://electron.atom.io'
twitter_username: ElectronJS
github_username: electron
future: true
excerpt_separator: '---'
gems:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jemoji
latest_version: 1.3.5
current_node: 6.3.0
current_chrome: 52.0.2743.82
current_v8: 5.2.361.43
sass:
    style: compressed
available_versions:
    - v0.24.0
    - v0.25.0
    - v0.26.0
    - v0.27.0
    - v0.28.0
    - v0.29.0
    - v0.30.0
    - v0.31.0
    - v0.32.0
    - v0.33.0
    - v0.34.0
    - v0.35.0
    - v0.36.0
    - v0.36.3
    - v0.36.4
    - v0.36.5
    - v0.36.6
    - v0.36.7
    - v0.36.8
    - v0.36.9
    - v0.36.10
    - v0.36.11
    - v0.37.0
    - v0.37.1
    - v0.37.2
    - v0.37.3
    - v0.37.4
    - v0.37.5
    - v0.37.6
    - v0.37.7
    - v0.37.8
    - v1.0.0
    - v1.0.1
    - v1.1.0
    - v1.1.1
    - v1.1.2
    - v1.1.3
    - v1.2.0
    - v1.2.1
    - v1.2.2
    - v1.2.3
    - v1.2.4
    - v1.2.5
    - v1.2.6
    - v1.2.7
    - v1.2.8
    - v1.3.0
    - v1.3.1
    - v1.3.2
    - v1.3.3
    - v1.3.4
    - v1.3.5
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:year/:month/:day/:title'}}
    - {scope: {path: ""}, values: {image: {path: /images/opengraph.png, width: 1200, height: 630}}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
include:
    - _pages
google_site_verification: eOAFtDphTbbm4OPKva2d3Z0Z_2bBxWMGdkD0IRQ6VeA
twitter:
    username: ElectronJS
logo: /images/opengraph.png
