title: Electron
email: atom@github.com
description: 'Build cross platform desktop apps with web technologies'
baseurl: 'http://electron.atom.io'
twitter_username: ElectronJS
github_username: atom
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
gems:
    - jekyll-redirect-from
latest_version: v0.37.8
current_node: 5.10.0
current_chrome: 49.0.2623.75
current_v8: 4.9.385.28
available_versions:
    - v0.24.0
    - v0.25.0
    - v0.26.0
    - v0.27.0
    - v0.28.0
    - v0.29.0
    - v0.30.0
    - v0.31.0
    - v0.32.0
    - v0.33.0
    - v0.34.0
    - v0.35.0
    - v0.36.0
    - v0.36.3
    - v0.36.4
    - v0.36.5
    - v0.36.6
    - v0.36.7
    - v0.36.8
    - v0.36.9
    - v0.36.10
    - v0.36.11
    - v0.37.0
    - v0.37.1
    - v0.37.2
    - v0.37.3
    - v0.37.4
    - v0.37.5
    - v0.37.6
    - v0.37.7
    - v0.37.8
collections:
    docs: {output: true, permalink: '/docs/:path/'}
defaults:
    - {scope: {type: docs}, values: {layout: docs}}
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Grunfile.js
    - package.json
    - script
    - spec
