# Site settings
title: Electron
email: atom@github.com
description: Build cross platform desktop apps with web technologies
baseurl: http://electron.atom.io
twitter_username: AtomEditor
github_username:  atom

# Build settings
markdown: kramdown
