# Site settings
title: Electron
email: electron@atom.io
description: Cross Platform Application Shell
url: http://electron.atom.io
twitter_username: AtomEditor
github_username:  atom

# Build settings
markdown: kramdown
