# Site settings
title: Electron
email: atom@github.com
description: Cross Platform Desktop Application Shell
baseurl: http://electron.atom.io
twitter_username: AtomEditor
github_username:  atom

# Build settings
markdown: kramdown
